# Generated by Django 4.1.7 on 2023-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_nume', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefon', models.CharField(max_length=20)),
                ('mesaj', models.TextField()),
            ],
        ),
    ]
