# Generated by Django 4.1.7 on 2023-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
